services:
  loki:
    image: grafana/loki
    restart: always
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD", "wget", "-O-", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 10s

  fotobuch:
    image: fotobuch-local:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./upload:/upload
    environment:
      LOKI_HOST: http://loki
      LOKI_PORT: 3100
      PORT: 80
      HOST: localhost
      FILE_UPLOAD_DEST: /upload
      ENVIRONMENT: LOCAL
      FRONTEND_PATH: /frontend
    depends_on:
      - loki